/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 nfc.gltf --transform
Author: Stichting Consortium Beroepsonderwijs (https://sketchfab.com/scb3d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rfid-readwrite-module-rc522-09a7fab0dd574bd1bbaa267e78ffd996
Title: RFID read/write module RC522
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/nfc-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group position={[0, -0.22, 0.07]}>
            <mesh geometry={nodes.Boole_Front_0.geometry} material={materials.Front} />
            <mesh geometry={nodes.Boole_Side_0.geometry} material={materials.Side} />
            <mesh geometry={nodes.Boole_Back_0.geometry} material={materials.Back} />
          </group>
          <group position={[-1.45, 2.67, 0.15]}>
            <mesh geometry={nodes.Cuerpo1_3__LED_0.geometry} material={materials.material} />
            <mesh geometry={nodes.Cuerpo2_3__Chrome_0.geometry} material={materials.Chrome} position={[-0.11, 0, 0]} />
          </group>
          <group position={[-0.01, 1.5, 0.15]}>
            <group position={[-1.47, 0.87, 0]} rotation={[0, 0, -Math.PI / 2]}>
              <mesh geometry={nodes.Capacitor_v1_Black_Diode_0.geometry} material={materials.Black_Diode} />
              <mesh geometry={nodes.Capacitor_v1_Chrome_0.geometry} material={materials.Chrome} />
            </group>
            <group position={[-1.47, 0.59, 0]} rotation={[0, 0, -Math.PI / 2]}>
              <mesh geometry={nodes.Capacitor_v1_1_Black_Diode_0.geometry} material={materials.Black_Diode} />
              <mesh geometry={nodes.Capacitor_v1_1_Chrome_0.geometry} material={materials.Chrome} />
            </group>
            <group position={[-1.47, 0.3, 0]} rotation={[0, 0, -Math.PI / 2]}>
              <mesh geometry={nodes.Capacitor_v1_2_Black_Diode_0.geometry} material={materials.Black_Diode} />
              <mesh geometry={nodes.Capacitor_v1_2_Chrome_0.geometry} material={materials.Chrome} />
            </group>
            <group position={[-0.74, 0.57, 0]} rotation={[0, 0, -Math.PI / 2]}>
              <mesh geometry={nodes.Capacitor_v1_3_Black_Diode_0.geometry} material={materials.Black_Diode} />
              <mesh geometry={nodes.Capacitor_v1_3_Chrome_0.geometry} material={materials.Chrome} />
            </group>
            <group position={[0.8, 0.59, 0]} rotation={[0, 0, -Math.PI / 2]}>
              <mesh geometry={nodes.Capacitor_v1_4_Black_Diode_0.geometry} material={materials.Black_Diode} />
              <mesh geometry={nodes.Capacitor_v1_4_Chrome_0.geometry} material={materials.Chrome} />
            </group>
            <group position={[0.8, 0.3, 0]} rotation={[0, 0, -Math.PI / 2]}>
              <mesh geometry={nodes.Capacitor_v1_5_Black_Diode_0.geometry} material={materials.Black_Diode} />
              <mesh geometry={nodes.Capacitor_v1_5_Chrome_0.geometry} material={materials.Chrome} />
            </group>
            <group position={[-0.76, 0.89, 0]} rotation={[0, 0, -Math.PI / 2]}>
              <mesh geometry={nodes.Capacitor_v1_6_Chrome_0.geometry} material={materials.Chrome} />
              <mesh geometry={nodes.Capacitor_v1_6_Red_Diode_0.geometry} material={materials.Red_Diode} />
            </group>
            <group position={[0.8, 0.89, 0]} rotation={[0, 0, -Math.PI / 2]}>
              <mesh geometry={nodes.Capacitor_v1_7_Chrome_0.geometry} material={materials.Chrome} />
              <mesh geometry={nodes.Capacitor_v1_7_Red_Diode_0.geometry} material={materials.Red_Diode} />
            </group>
            <group position={[0.8, 0.02, 0]} rotation={[0, 0, -Math.PI / 2]}>
              <mesh geometry={nodes.Capacitor_v1_8_Chrome_0.geometry} material={materials.Chrome} />
              <mesh geometry={nodes.Capacitor_v1_8_Red_Diode_0.geometry} material={materials.Red_Diode} />
            </group>
            <group position={[-0.76, 0.3, 0]} rotation={[0, 0, -Math.PI / 2]}>
              <mesh geometry={nodes.Capacitor_v1_9_Chrome_0.geometry} material={materials.Chrome} />
              <mesh geometry={nodes.Capacitor_v1_9_Pink_Diode_0.geometry} material={materials.Pink_Diode} />
            </group>
            <group position={[-0.76, 0, 0]} rotation={[0, 0, -Math.PI / 2]}>
              <mesh geometry={nodes.Capacitor_v1_10_Chrome_0.geometry} material={materials.Chrome} />
              <mesh geometry={nodes.Capacitor_v1_10_Pink_Diode_0.geometry} material={materials.Pink_Diode} />
            </group>
            <group position={[-0.71, -1, 0]}>
              <mesh geometry={nodes.Capacitor_v1_11_Chrome_0.geometry} material={materials.Chrome} />
              <mesh geometry={nodes.Capacitor_v1_11_Pink_Diode_0.geometry} material={materials.Pink_Diode} />
            </group>
            <group position={[-0.14, -1, 0]}>
              <mesh geometry={nodes.Capacitor_v1_12_Chrome_0.geometry} material={materials.Chrome} />
              <mesh geometry={nodes.Capacitor_v1_12_Pink_Diode_0.geometry} material={materials.Pink_Diode} />
            </group>
            <group position={[0.15, -1, 0]}>
              <mesh geometry={nodes.Capacitor_v1_13_Chrome_0.geometry} material={materials.Chrome} />
              <mesh geometry={nodes.Capacitor_v1_13_Pink_Diode_0.geometry} material={materials.Pink_Diode} />
            </group>
            <group position={[0.74, -1, 0]}>
              <mesh geometry={nodes.Capacitor_v1_14_Chrome_0.geometry} material={materials.Chrome} />
              <mesh geometry={nodes.Capacitor_v1_14_Pink_Diode_0.geometry} material={materials.Pink_Diode} />
            </group>
            <group position={[1.36, 0.52, 0]}>
              <mesh geometry={nodes.Capacitor_v1_15_Chrome_0.geometry} material={materials.Chrome} />
              <mesh geometry={nodes.Capacitor_v1_15_Pink_Diode_0.geometry} material={materials.Pink_Diode} />
            </group>
            <group position={[1.34, 1.05, 0]}>
              <mesh geometry={nodes.Capacitor_v1_16_Chrome_0.geometry} material={materials.Chrome} />
              <mesh geometry={nodes.Capacitor_v1_16_Pink_Diode_0.geometry} material={materials.Pink_Diode} />
            </group>
            <group position={[-0.43, -1, 0]}>
              <mesh geometry={nodes.Capacitor_v1_17_Chrome_0.geometry} material={materials.Chrome} />
              <mesh geometry={nodes.Capacitor_v1_17_Gold_Diode_0.geometry} material={materials.Gold_Diode} />
            </group>
            <group position={[0.45, -1, 0]}>
              <mesh geometry={nodes.Capacitor_v1_18_Chrome_0.geometry} material={materials.Chrome} />
              <mesh geometry={nodes.Capacitor_v1_18_Gold_Diode_0.geometry} material={materials.Gold_Diode} />
            </group>
          </group>
          <group position={[0.02, 1.99, 0.15]} rotation={[0, 0, -Math.PI]}>
            <mesh geometry={nodes.Cuerpo1_4__Black_Plastic_0.geometry} material={materials.Black_Plastic} />
            <mesh geometry={nodes.Cuerpo12_1__Chrome_0.geometry} material={materials.Chrome} rotation={[0, 0, Math.PI]} />
          </group>
          <mesh geometry={nodes.Cuerpo1_6__Black_Plastic_0.geometry} material={materials.Black_Plastic} position={[0.05, 2.81, 0.15]} />
          <mesh geometry={nodes.OSC_v9_Chrome_0.geometry} material={materials.Chrome} position={[1.72, 2.3, 0.15]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Cuerpo1_5__Chrome_0.geometry} material={materials.Chrome} position={[0.05, 2.81, 0.23]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/nfc-transformed.glb')
